version: '3'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/portfolio/priya
    environment:
      - NODE_ENV=production
    command: npm start
